import { useState, useRef, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Image, Loader2, Check, Link2, Facebook, ExternalLink } from 'lucide-react';
import { toast } from 'sonner';
import html2canvas from 'html2canvas';
import { MarketingListing, formatListingPrice } from '@/data/marketingListings';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/lib/auth';
import logo from '@/assets/logo.jpg';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const bannerOptions = [
  { value: 'auto', label: 'Auto-detect from Status' },
  { value: 'new-listing', label: 'NEW LISTING' },
  { value: 'just-sold', label: 'JUST SOLD' },
  { value: 'price-change', label: 'PRICE CHANGE' },
  { value: 'open-house', label: 'OPEN HOUSE' },
  { value: 'under-contract', label: 'UNDER CONTRACT' },
  { value: 'back-on-market', label: 'BACK ON MARKET' },
];

function getBannerText(listing: MarketingListing, override: string): string {
  if (override !== 'auto') {
    return bannerOptions.find(o => o.value === override)?.label || override.toUpperCase();
  }
  switch (listing.status) {
    case 'sold': return 'JUST SOLD';
    case 'pending': return 'UNDER CONTRACT';
    case 'contingent': return 'UNDER CONTRACT';
    case 'active':
    default:
      return listing.daysOnMarket <= 7 ? 'NEW LISTING' : 'FOR SALE';
  }
}

interface AdGeneratorPanelProps {
  listing: MarketingListing;
  autoGenerate?: boolean;
}

const AdGeneratorPanel = ({ listing, autoGenerate = false }: AdGeneratorPanelProps) => {
  const { user } = useAuth();
  const [bannerType, setBannerType] = useState('auto');
  const [generating, setGenerating] = useState(false);
  const [posting, setPosting] = useState(false);
  const [posted, setPosted] = useState(false);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [heroDataUrl, setHeroDataUrl] = useState<string | null>(null);
  const [fbConnected, setFbConnected] = useState(false);
  const [fbPageName, setFbPageName] = useState('');
  const [fbLoading, setFbLoading] = useState(true);
  const adRef = useRef<HTMLDivElement>(null);
  const listingUrl = `https://listings.sellfor1percent.com/listing/${listing.id}`;
  const hasAutoGenerated = useRef(false);

  const bannerText = getBannerText(listing, bannerType);
  const heroPhoto = listing.photos?.[0];
  const fullAddress = `${listing.address}, ${listing.city}, ${listing.state} ${listing.zip}`;

  const agentPhoneMap: Record<string, string> = {
    'David E Barlow': '614-778-6616',
    'Jaysen E Barlow': '614-579-1442',
    'Jaime Barlow': '614-493-8541',
    'Jaime E Barlow': '614-493-8541',
  };
  const agentPhone = (listing.agent?.phone && !/^\*+$/.test(listing.agent.phone))
    ? listing.agent.phone
    : (listing.agent?.name ? agentPhoneMap[listing.agent.name] || '' : '');

  // Check Facebook connection
  useEffect(() => {
    if (!user) return;
    (async () => {
      setFbLoading(true);
      try {
        const { data } = await supabase
          .from('facebook_oauth_tokens' as any)
          .select('page_name, access_token')
          .eq('agent_id', user.id)
          .maybeSingle();
        if (data && (data as any).access_token) {
          setFbConnected(true);
          setFbPageName((data as any).page_name || 'Facebook');
        }
      } catch (err) {
        console.error('[FB] check error:', err);
      }
      setFbLoading(false);
    })();
  }, [user]);

  const generateRef = useRef<(() => void) | null>(null);

  // Auto-generate when panel opens
  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated.current && !fbLoading) {
      hasAutoGenerated.current = true;
      // Small delay to ensure hidden template is rendered
      setTimeout(() => {
        generateRef.current?.();
      }, 300);
    }
  }, [autoGenerate, fbLoading]);

  const connectFacebook = async () => {
    try {
      const resp = await fetch(`${SUPABASE_URL}/functions/v1/facebook-auth-url`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${ANON_KEY}` },
        body: JSON.stringify({ agent_id: user!.id, app_origin: window.location.origin }),
      });
      const data = await resp.json();
      if (data.error) throw new Error(data.error);
      window.open(data.auth_url, '_blank');
    } catch (err: any) {
      toast.error(err.message || 'Failed to start Facebook login');
    }
  };

  // Proxy external image through edge function to bypass CORS
  const toDataUrl = async (url: string): Promise<string> => {
    const resp = await fetch(`${SUPABASE_URL}/functions/v1/proxy-image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${ANON_KEY}` },
      body: JSON.stringify({ url }),
    });
    const data = await resp.json();
    if (data.error) throw new Error(data.error);
    return data.data;
  };


  const generateAd = async () => {
    if (!adRef.current) return;
    setGenerating(true);
    try {
      // Pre-load hero photo as data URL to avoid CORS
      if (heroPhoto && !heroDataUrl) {
        try {
          const dataUrl = await toDataUrl(heroPhoto);
          setHeroDataUrl(dataUrl);
          // Wait for React to re-render with the data URL, then re-trigger
          setTimeout(() => generateAfterImageLoad(dataUrl), 200);
          return;
        } catch {
          console.warn('Could not load hero photo, generating without it');
        }
      }
      await captureCanvas();
    } catch (err: any) {
      toast.error('Failed to generate ad image');
      console.error(err);
      setGenerating(false);
    }
  };

  generateRef.current = generateAd;

  const generateAfterImageLoad = async (_dataUrl: string) => {
    try {
      await captureCanvas();
    } catch (err: any) {
      toast.error('Failed to generate ad image');
      console.error(err);
      setGenerating(false);
    }
  };

  const captureCanvas = async () => {
    if (!adRef.current) { setGenerating(false); return; }
    try {
      const canvas = await html2canvas(adRef.current, {
        scale: 3,
        useCORS: true,
        allowTaint: false,
        backgroundColor: '#1a1a2e',
        width: 1200,
        height: 630,
        scrollX: 0,
        scrollY: 0,
      });
      const url = canvas.toDataURL('image/png');
      setPreviewUrl(url);
      setPosted(false);
      toast.success('Ad generated! Ready to post.');
    } catch (err: any) {
      toast.error('Failed to generate ad image');
      console.error(err);
    }
    setGenerating(false);
  };

  const postToFacebook = async () => {
    if (!previewUrl || !user) return;
    setPosting(true);
    try {
      // Convert data URL to blob
      const res = await fetch(previewUrl);
      const blob = await res.blob();
      const fileName = `ad-${listing.mlsNumber || listing.id}-${Date.now()}.png`;

      // Upload to storage
      const { data: uploadData, error: uploadErr } = await supabase.storage
        .from('ad-images')
        .upload(fileName, blob, { contentType: 'image/png', upsert: true });

      if (uploadErr) throw new Error(`Upload failed: ${uploadErr.message}`);

      // Get public URL
      const { data: urlData } = supabase.storage.from('ad-images').getPublicUrl(fileName);
      const publicUrl = urlData.publicUrl;

      // Post to Facebook with the image
      const price = formatListingPrice(listing.price);
      const message = `🏠 ${bannerText}\n\n📍 ${fullAddress}\n💰 ${price}\n🛏️ ${listing.beds} Beds | 🛁 ${listing.baths} Baths | 📐 ${listing.sqft.toLocaleString()} sqft\n\n👉 More info: ${listingUrl}\n\n📞 Contact ${listing.agent?.name || 'us'} for details!\n\n#RealEstate #${listing.city.replace(/\s/g, '')} #HomeForSale`;

      const postResp = await fetch(`${SUPABASE_URL}/functions/v1/facebook-post-listing`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${ANON_KEY}` },
        body: JSON.stringify({
          agent_id: user.id,
          message,
          photo_url: publicUrl,
          link: listingUrl,
        }),
      });
      const postData = await postResp.json();
      if (postData.error) throw new Error(postData.error);

      setPosted(true);
      toast.success('Ad posted to Facebook! 🎉');
      setTimeout(() => setPosted(false), 5000);
    } catch (err: any) {
      toast.error(err.message || 'Failed to post to Facebook');
    }
    setPosting(false);
  };

  return (
    <div className="bg-card border border-border rounded-lg p-5">
      <div className="flex items-center gap-2 mb-4">
        <Image className="w-5 h-5 text-primary" />
        <h3 className="text-lg font-bold text-card-foreground">Generate & Post Ad</h3>
      </div>

      {/* Facebook connection status */}
      {fbLoading ? (
        <div className="flex items-center gap-2 text-xs text-muted-foreground mb-3">
          <Loader2 className="w-3 h-3 animate-spin" /> Checking Facebook...
        </div>
      ) : fbConnected ? (
        <p className="text-xs text-muted-foreground mb-3 flex items-center gap-1">
          <Check className="w-3 h-3 text-emerald-500" />
          Connected to <span className="font-medium text-foreground">{fbPageName}</span>
        </p>
      ) : (
        <div className="mb-3">
          <Button onClick={connectFacebook} variant="outline" size="sm" className="w-full">
            <Link2 className="w-4 h-4 mr-2" /> Connect Facebook Page First
          </Button>
        </div>
      )}

      <div className="mb-4">
        <label className="text-xs font-medium text-muted-foreground mb-1.5 block">Banner Type</label>
        <Select value={bannerType} onValueChange={setBannerType}>
          <SelectTrigger className="w-full">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {bannerOptions.map(opt => (
              <SelectItem key={opt.value} value={opt.value}>{opt.label}</SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {/* Hidden ad template for html2canvas — 1200×630 for Facebook link share */}
      <div style={{ position: 'fixed', left: '-9999px', top: 0, width: 1200, height: 630, overflow: 'visible', zIndex: -1 }}>
        <div
          ref={adRef}
          style={{
            width: 1200, minWidth: 1200, height: 630, minHeight: 630,
            fontFamily: "'Segoe UI', Arial, sans-serif",
            position: 'relative', overflow: 'hidden',
            backgroundColor: '#1a1a2e',
          }}
        >
          {(heroDataUrl || heroPhoto) ? (
            <img src={heroDataUrl || heroPhoto} alt="" style={{ width: '100%', height: '100%', position: 'absolute', top: 0, left: 0,
              objectFit: 'cover', objectPosition: 'center' }} />
          ) : (
            <div style={{ width: '100%', height: '100%', position: 'absolute', top: 0, left: 0,
              background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)' }} />
          )}
          <div style={{ position: 'absolute', inset: 0,
            background: 'linear-gradient(to bottom, rgba(0,0,0,0.05) 0%, rgba(0,0,0,0.1) 40%, rgba(0,0,0,0.65) 70%, rgba(0,0,0,0.85) 100%)' }} />

           {/* Red banner */}
           <div style={{
             position: 'absolute', top: 0, left: 0, right: 0,
             backgroundColor: '#cc0000', color: '#ffffff', textAlign: 'center',
             padding: '14px 100px 32px 100px', fontSize: 36, fontWeight: 800,
             letterSpacing: 5, textTransform: 'uppercase', zIndex: 10,
           }}>
            {bannerText}
            <img src={logo} alt="Logo" style={{ position: 'absolute', right: 20, top: '50%', transform: 'translateY(-50%)', height: 44, borderRadius: 4 }} />
          </div>

          {/* Property details */}
          <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, padding: '20px 36px', zIndex: 10 }}>
            <div style={{ color: '#ffffff', fontSize: 52, fontWeight: 800, marginBottom: 4,
              textShadow: '0 3px 6px rgba(0,0,0,0.5)' }}>
              {formatListingPrice(listing.price)}
            </div>
            <div style={{ color: '#e0e0e0', fontSize: 24, fontWeight: 600, marginBottom: 12,
              textShadow: '0 2px 4px rgba(0,0,0,0.5)' }}>
              {fullAddress}
            </div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between',
              marginBottom: 14, textShadow: '0 2px 4px rgba(0,0,0,0.5)' }}>
              <div style={{ display: 'flex', gap: 30, color: '#ffffff', fontSize: 22, fontWeight: 600 }}>
                <span>{listing.beds} Beds</span>
                <span>{listing.baths} Baths</span>
                <span>{(listing.sqft || 0).toLocaleString()} Sq Ft</span>
              </div>
              <div style={{ backgroundColor: '#cc0000', borderRadius: 8,
                 paddingLeft: 18, paddingRight: 18, paddingTop: 10, paddingBottom: 20, textAlign: 'center' }}>
                 <span style={{ color: '#ffffff', fontSize: 20, fontWeight: 800, letterSpacing: 1, whiteSpace: 'nowrap' }}>
                   Click for more info
                 </span>
               </div>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between',
              backgroundColor: 'rgba(0,0,0,0.5)', borderRadius: 8, padding: '10px 18px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                <img src={logo} alt="Logo" style={{ height: 40, borderRadius: 6 }} />
                <div>
                  <div style={{ color: '#ffffff', fontSize: 18, fontWeight: 700 }}>
                    {listing.agent?.name || 'Agent'}
                  </div>
                   <div style={{ color: '#bbbbbb', fontSize: 15 }}>
                     {agentPhone}
                   </div>
                </div>
              </div>
              <div style={{ color: '#cccccc', fontSize: 15 }}>MLS# {listing.mlsNumber}</div>
            </div>
          </div>
        </div>
      </div>

      <Button onClick={generateAd} disabled={generating} className="w-full mb-3" size="sm">
        {generating ? (
          <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Generating...</>
        ) : (
          <><Image className="w-4 h-4 mr-2" /> {previewUrl ? 'Regenerate' : 'Generate'} Ad Image</>
        )}
      </Button>

      {previewUrl && (
        <>
          <div className="border border-border rounded-lg overflow-hidden mb-3">
            <img src={previewUrl} alt="Generated ad" className="w-full" />
          </div>

          {fbConnected && (
            <Button
              onClick={postToFacebook}
              disabled={posting || posted}
              className="w-full"
              size="sm"
            >
              {posted ? (
                <><Check className="w-4 h-4 mr-2" /> Posted!</>
              ) : posting ? (
                <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Posting...</>
              ) : (
                <><Facebook className="w-4 h-4 mr-2" /> Post Ad to Facebook</>
              )}
            </Button>
          )}
        </>
      )}
    </div>
  );
};

export default AdGeneratorPanel;
