import { useState, useRef, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Image, Loader2, Check, Link2, Facebook, DollarSign, Calendar, MapPin } from 'lucide-react';
import { toast } from 'sonner';
import { MarketingListing, formatListingPrice } from '@/data/marketingListings';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/lib/auth';
import { renderAdCanvas } from './adCanvasRenderer';
import { renderInstagramCanvas } from './instagramAdRenderer';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const bannerOptions = [
  { value: 'auto', label: 'Auto-detect from Status' },
  { value: 'new-listing', label: 'NEW LISTING' },
  { value: 'just-sold', label: 'JUST SOLD' },
  { value: 'price-change', label: 'PRICE CHANGE' },
  { value: 'open-house', label: 'OPEN HOUSE' },
  { value: 'under-contract', label: 'UNDER CONTRACT' },
  { value: 'back-on-market', label: 'BACK ON MARKET' },
];

const budgetOptions = [
  { value: '5', label: '$5/day' },
  { value: '10', label: '$10/day' },
  { value: '15', label: '$15/day' },
  { value: '20', label: '$20/day' },
  { value: '25', label: '$25/day' },
  { value: '50', label: '$50/day' },
  { value: '100', label: '$100/day' },
];

const durationOptions = [
  { value: '3', label: '3 days' },
  { value: '5', label: '5 days' },
  { value: '7', label: '7 days' },
  { value: '14', label: '14 days' },
  { value: '30', label: '30 days' },
];

const radiusOptions = [
  { value: '15', label: '15 Miles' },
  { value: '20', label: '20 Miles' },
  { value: '25', label: '25 Miles' },
  { value: '30', label: '30 Miles' },
];

function getBannerText(listing: MarketingListing, override: string): string {
  if (override !== 'auto') {
    return bannerOptions.find(o => o.value === override)?.label || override.toUpperCase();
  }
  switch (listing.status) {
    case 'sold': return 'JUST SOLD';
    case 'pending': return 'UNDER CONTRACT';
    case 'contingent': return 'UNDER CONTRACT';
    case 'active':
    default:
      return listing.daysOnMarket <= 7 ? 'NEW LISTING' : 'FOR SALE';
  }
}

interface AdGeneratorPanelProps {
  listing: MarketingListing;
  autoGenerate?: boolean;
}

const AdGeneratorPanel = ({ listing, autoGenerate = false }: AdGeneratorPanelProps) => {
  const { user } = useAuth();
  const [bannerType, setBannerType] = useState('auto');
  const [generating, setGenerating] = useState(false);
  const [posting, setPosting] = useState(false);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [fbPreviewUrl, setFbPreviewUrl] = useState<string | null>(null);
  const [heroDataUrl, setHeroDataUrl] = useState<string | null>(null);
  const [fbConnected, setFbConnected] = useState(false);
  const [fbPageName, setFbPageName] = useState('');
  const [fbLoading, setFbLoading] = useState(true);
  const [posted, setPosted] = useState(false);
  const [postId, setPostId] = useState<string | null>(null);
  
  // Boost config
  const [boostEnabled, setBoostEnabled] = useState(false);
  const [boostConfig, setBoostConfig] = useState({ 
    dailyBudget: '10', 
    duration: '7', 
    radius: '15',
    targetZip: listing.zip 
  });
  
  const listingUrl = `https://listings.sellfor1percent.com/listing/${listing.id}`;
  const ogListingUrl = `${SUPABASE_URL}/functions/v1/og-listing?id=${listing.id}`;
  const hasAutoGenerated = useRef(false);

  const bannerText = getBannerText(listing, bannerType);
  const heroPhoto = listing.photos?.[0];
  const fullAddress = `${listing.address}, ${listing.city}, ${listing.state} ${listing.zip}`;

  const agentPhoneMap: Record<string, string> = {
    'David E Barlow': '614-778-6616',
    'Jaysen E Barlow': '614-579-1442',
    'Jaime Barlow': '614-493-8541',
    'Jaime E Barlow': '614-493-8541',
  };
  const agentPhone = (listing.agent?.phone && !/^\*+$/.test(listing.agent.phone))
    ? listing.agent.phone
    : (listing.agent?.name ? agentPhoneMap[listing.agent.name] || '' : '');

  // Check Facebook connection
  useEffect(() => {
    if (!user) return;
    (async () => {
      setFbLoading(true);
      try {
        const { data } = await supabase
          .from('facebook_oauth_tokens' as any)
          .select('page_name, access_token')
          .eq('agent_id', user.id)
          .maybeSingle();
        if (data && (data as any).access_token) {
          setFbConnected(true);
          setFbPageName((data as any).page_name || 'Facebook');
        }
      } catch (err) {
        console.error('[FB] check error:', err);
      }
      setFbLoading(false);
    })();
  }, [user]);

  const generateRef = useRef<(() => void) | null>(null);

  // Auto-generate when panel opens
  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated.current && !fbLoading) {
      hasAutoGenerated.current = true;
      setTimeout(() => {
        generateRef.current?.();
      }, 300);
    }
  }, [autoGenerate, fbLoading]);

  const connectFacebook = async () => {
    try {
      const resp = await fetch(`${SUPABASE_URL}/functions/v1/facebook-auth-url`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${ANON_KEY}` },
        body: JSON.stringify({ agent_id: user!.id, app_origin: window.location.origin }),
      });
      const data = await resp.json();
      if (data.error) throw new Error(data.error);
      window.open(data.auth_url, '_blank');
    } catch (err: any) {
      toast.error(err.message || 'Failed to start Facebook login');
    }
  };

  const toDataUrl = async (url: string): Promise<string> => {
    const resp = await fetch(`${SUPABASE_URL}/functions/v1/proxy-image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${ANON_KEY}` },
      body: JSON.stringify({ url }),
    });
    const data = await resp.json();
    if (data.error) throw new Error(data.error);
    return data.data;
  };

  const generateAd = async () => {
    setGenerating(true);
    try {
      let dataUrl = heroDataUrl;
      if (heroPhoto && !dataUrl) {
        try {
          dataUrl = await toDataUrl(heroPhoto);
          setHeroDataUrl(dataUrl);
        } catch {
          console.warn('Could not load hero photo, generating without it');
        }
      }
      const renderOpts = { listing, bannerText, heroDataUrl: dataUrl, agentPhone };
      // Generate both Instagram (square preview) and Facebook (landscape) images
      const [igUrl, fbUrl] = await Promise.all([
        renderInstagramCanvas(renderOpts),
        renderAdCanvas(renderOpts),
      ]);
      setPreviewUrl(igUrl);
      setFbPreviewUrl(fbUrl);
      setPosted(false);
      toast.success('Ad generated! Ready to post.');
    } catch (err: any) {
      toast.error('Failed to generate ad image');
      console.error(err);
    }
    setGenerating(false);
  };

  generateRef.current = generateAd;

  const postToFacebook = async () => {
    if (!previewUrl || !fbPreviewUrl || !user) return;
    setPosting(true);
    try {
      const ts = Date.now();

      // Upload both images in parallel
      const [igBlob, fbBlob] = await Promise.all([
        fetch(previewUrl).then(r => r.blob()),
        fetch(fbPreviewUrl).then(r => r.blob()),
      ]);
      const igFileName = `ig-${listing.mlsNumber || listing.id}-${ts}.png`;
      const fbFileName = `fb-${listing.mlsNumber || listing.id}-${ts}.png`;

      const [igUpload, fbUpload] = await Promise.all([
        supabase.storage.from('ad-images').upload(igFileName, igBlob, { contentType: 'image/png', upsert: true }),
        supabase.storage.from('ad-images').upload(fbFileName, fbBlob, { contentType: 'image/png', upsert: true }),
      ]);
      if (igUpload.error) throw new Error(`IG upload failed: ${igUpload.error.message}`);
      if (fbUpload.error) throw new Error(`FB upload failed: ${fbUpload.error.message}`);

      const igPublicUrl = supabase.storage.from('ad-images').getPublicUrl(igFileName).data.publicUrl;
      const fbPublicUrl = supabase.storage.from('ad-images').getPublicUrl(fbFileName).data.publicUrl;

      // Build OG URL with FB image for Facebook link share
      const timestamp = Math.floor(ts / 1000);
      const ogUrlWithImage = `${ogListingUrl}&image=${encodeURIComponent(fbPublicUrl)}&v=${timestamp}`;

      // Post to Facebook + Instagram
      const price = formatListingPrice(listing.price);
      const phoneDisplay = agentPhone ? ` at ${agentPhone}` : '';
      const message = `🏠 ${bannerText}\n\n📍 ${fullAddress}\n💰 ${price}\n🛏️ ${listing.beds} Beds | 🛁 ${listing.baths} Baths | 📐 ${listing.sqft.toLocaleString()} sqft\n\n👉 For More info Copy and Paste This Link: ${listingUrl}\n\n📞 Contact ${listing.agent?.name || 'us'}${phoneDisplay} for details!\n\n#RealEstate #${listing.city.replace(/\s/g, '')} #HomeForSale`;

      const postResp = await fetch(`${SUPABASE_URL}/functions/v1/facebook-post-listing`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${ANON_KEY}` },
        body: JSON.stringify({
          agent_id: user.id,
          message,
          link: ogUrlWithImage,
          instagram_image_url: igPublicUrl,
        }),
      });
      const postData = await postResp.json();
      console.log('[FB] Post response:', postData);
      if (postData.error) throw new Error(postData.error);

      const returnedPostId = postData.post_id || postData.id || null;
      console.log('[FB] Setting postId to:', returnedPostId);
      setPosted(true);
      setPostId(returnedPostId);

      // Handle boost if enabled
      if (boostEnabled && returnedPostId) {
        try {
          const boostResp = await fetch(`${SUPABASE_URL}/functions/v1/boost-facebook-post`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${ANON_KEY}` },
            body: JSON.stringify({
              agent_id: user.id,
              post_id: returnedPostId,
              daily_budget: Number(boostConfig.dailyBudget),
              duration_days: Number(boostConfig.duration),
              radius_miles: Number(boostConfig.radius),
              zip: boostConfig.targetZip || undefined,
            }),
          });
          const boostData = await boostResp.json();
          if (boostData.error) throw new Error(boostData.error);
          toast.success(`Posted and boosted! $${Number(boostConfig.dailyBudget) * Number(boostConfig.duration)} over ${boostConfig.duration} days 🚀`);
        } catch (err: any) {
          toast.warning('Post created but boost failed: ' + (err.message || 'Unknown error'));
        }
      } else {
        toast.success('Ad posted to Facebook! 🎉');
      }

      // Reset boost state after posting
      setBoostEnabled(false);
    } catch (err: any) {
      toast.error(err.message || 'Failed to post to Facebook');
    }
    setPosting(false);
  };

  return (
    <div className="bg-card border border-border rounded-lg p-5">
      <div className="flex items-center gap-2 mb-4">
        <Image className="w-5 h-5 text-primary" />
        <h3 className="text-lg font-bold text-card-foreground">Generate & Post Ad</h3>
      </div>

      {/* Facebook connection status */}
      {fbLoading ? (
        <div className="flex items-center gap-2 text-xs text-muted-foreground mb-3">
          <Loader2 className="w-3 h-3 animate-spin" /> Checking Facebook...
        </div>
      ) : fbConnected ? (
        <p className="text-xs text-muted-foreground mb-3 flex items-center gap-1">
          <Check className="w-3 h-3 text-emerald-500" />
          Connected to <span className="font-medium text-foreground">{fbPageName}</span>
        </p>
      ) : (
        <div className="mb-3">
          <Button onClick={connectFacebook} variant="outline" size="sm" className="w-full">
            <Link2 className="w-4 h-4 mr-2" /> Connect Facebook Page First
          </Button>
        </div>
      )}

      <div className="mb-4">
        <label className="text-xs font-medium text-muted-foreground mb-1.5 block">Banner Type</label>
        <Select value={bannerType} onValueChange={setBannerType}>
          <SelectTrigger className="w-full">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {bannerOptions.map(opt => (
              <SelectItem key={opt.value} value={opt.value}>{opt.label}</SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <Button onClick={generateAd} disabled={generating} className="w-full mb-3 !bg-green-600 hover:!bg-green-700 !text-white" size="sm">
        {generating ? (
          <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Generating...</>
        ) : (
          <><Image className="w-4 h-4 mr-2" /> {previewUrl ? 'Regenerate' : 'Generate'} Ad Image</>
        )}
      </Button>

      {previewUrl && (
        <>
          <div className="border border-border rounded-lg overflow-hidden mb-3">
            <img src={previewUrl} alt="Generated ad" className="w-full" />
          </div>

          {/* Boost toggle */}
          {fbConnected && (
            <div className="border border-border rounded-lg p-3 mb-3">
              <div className="flex items-center gap-2 mb-3">
                <Checkbox
                  id="boost-toggle"
                  checked={boostEnabled}
                  onCheckedChange={(checked) => setBoostEnabled(checked as boolean)}
                />
                <label htmlFor="boost-toggle" className="text-sm font-medium text-card-foreground cursor-pointer">
                  Boost this post
                </label>
              </div>

              {boostEnabled && (
                <div className="space-y-3 pt-3 border-t border-border">
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="text-xs font-medium text-muted-foreground mb-1 block">
                        <DollarSign className="w-3 h-3 inline mr-1" />Daily Budget
                      </label>
                      <Select value={boostConfig.dailyBudget} onValueChange={(val) => setBoostConfig({ ...boostConfig, dailyBudget: val })}>
                        <SelectTrigger className="w-full">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          {budgetOptions.map(opt => (
                            <SelectItem key={opt.value} value={opt.value}>{opt.label}</SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>

                    <div>
                      <label className="text-xs font-medium text-muted-foreground mb-1 block">
                        <Calendar className="w-3 h-3 inline mr-1" />Duration
                      </label>
                      <Select value={boostConfig.duration} onValueChange={(val) => setBoostConfig({ ...boostConfig, duration: val })}>
                        <SelectTrigger className="w-full">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          {durationOptions.map(opt => (
                            <SelectItem key={opt.value} value={opt.value}>{opt.label}</SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="text-xs font-medium text-muted-foreground mb-1 block">
                        <MapPin className="w-3 h-3 inline mr-1" />Targeting Radius
                      </label>
                      <Select value={boostConfig.radius} onValueChange={(val) => setBoostConfig({ ...boostConfig, radius: val })}>
                        <SelectTrigger className="w-full">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          {radiusOptions.map(opt => (
                            <SelectItem key={opt.value} value={opt.value}>{opt.label}</SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>

                    <div>
                      <label className="text-xs font-medium text-muted-foreground mb-1 block">
                        <MapPin className="w-3 h-3 inline mr-1" />Zip Code
                      </label>
                      <Input
                        value={boostConfig.targetZip}
                        onChange={(e) => setBoostConfig({ ...boostConfig, targetZip: e.target.value })}
                        placeholder="Zip code"
                        className="text-sm"
                        maxLength={5}
                      />
                    </div>
                  </div>

                  <p className="text-xs text-muted-foreground">
                    Total: ${Number(boostConfig.dailyBudget) * Number(boostConfig.duration)} over {boostConfig.duration} days
                  </p>
                </div>
              )}
            </div>
          )}

          {fbConnected && (
            <Button
              onClick={postToFacebook}
              disabled={posting || posted}
              className="w-full !bg-green-600 hover:!bg-green-700 !text-white"
              size="sm"
            >
              {posted ? (
                <><Check className="w-4 h-4 mr-2" /> Posted!</>
              ) : posting ? (
                <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Posting...</>
              ) : (
                <><Facebook className="w-4 h-4 mr-2" /> Post Ad to Facebook & Instagram</>
              )}
            </Button>
          )}
        </>
      )}
    </div>
  );
};

export default AdGeneratorPanel;
