import { useState, useRef, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Image, Loader2, Check, Link2, Facebook, ExternalLink } from 'lucide-react';
import { toast } from 'sonner';
import { MarketingListing, formatListingPrice } from '@/data/marketingListings';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/lib/auth';
import { renderAdCanvas } from './adCanvasRenderer';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const bannerOptions = [
  { value: 'auto', label: 'Auto-detect from Status' },
  { value: 'new-listing', label: 'NEW LISTING' },
  { value: 'just-sold', label: 'JUST SOLD' },
  { value: 'price-change', label: 'PRICE CHANGE' },
  { value: 'open-house', label: 'OPEN HOUSE' },
  { value: 'under-contract', label: 'UNDER CONTRACT' },
  { value: 'back-on-market', label: 'BACK ON MARKET' },
];

function getBannerText(listing: MarketingListing, override: string): string {
  if (override !== 'auto') {
    return bannerOptions.find(o => o.value === override)?.label || override.toUpperCase();
  }
  switch (listing.status) {
    case 'sold': return 'JUST SOLD';
    case 'pending': return 'UNDER CONTRACT';
    case 'contingent': return 'UNDER CONTRACT';
    case 'active':
    default:
      return listing.daysOnMarket <= 7 ? 'NEW LISTING' : 'FOR SALE';
  }
}

interface AdGeneratorPanelProps {
  listing: MarketingListing;
  autoGenerate?: boolean;
}

const AdGeneratorPanel = ({ listing, autoGenerate = false }: AdGeneratorPanelProps) => {
  const { user } = useAuth();
  const [bannerType, setBannerType] = useState('auto');
  const [generating, setGenerating] = useState(false);
  const [posting, setPosting] = useState(false);
  const [posted, setPosted] = useState(false);
  const [postId, setPostId] = useState<string | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [heroDataUrl, setHeroDataUrl] = useState<string | null>(null);
  const [fbConnected, setFbConnected] = useState(false);
  const [fbPageName, setFbPageName] = useState('');
  const [fbLoading, setFbLoading] = useState(true);
  
  const listingUrl = `https://listings.sellfor1percent.com/listing/${listing.id}`;
  // Use the proxy OG URL for Facebook link posts so Facebook scrapes dynamic meta tags
  const ogListingUrl = `https://formoreinfo.sellfor1percent.com/og-listing?id=${listing.id}`;
  const hasAutoGenerated = useRef(false);

  const bannerText = getBannerText(listing, bannerType);
  const heroPhoto = listing.photos?.[0];
  const fullAddress = `${listing.address}, ${listing.city}, ${listing.state} ${listing.zip}`;

  const agentPhoneMap: Record<string, string> = {
    'David E Barlow': '614-778-6616',
    'Jaysen E Barlow': '614-579-1442',
    'Jaime Barlow': '614-493-8541',
    'Jaime E Barlow': '614-493-8541',
  };
  const agentPhone = (listing.agent?.phone && !/^\*+$/.test(listing.agent.phone))
    ? listing.agent.phone
    : (listing.agent?.name ? agentPhoneMap[listing.agent.name] || '' : '');

  // Check Facebook connection
  useEffect(() => {
    if (!user) return;
    (async () => {
      setFbLoading(true);
      try {
        const { data } = await supabase
          .from('facebook_oauth_tokens' as any)
          .select('page_name, access_token')
          .eq('agent_id', user.id)
          .maybeSingle();
        if (data && (data as any).access_token) {
          setFbConnected(true);
          setFbPageName((data as any).page_name || 'Facebook');
        }
      } catch (err) {
        console.error('[FB] check error:', err);
      }
      setFbLoading(false);
    })();
  }, [user]);

  const generateRef = useRef<(() => void) | null>(null);

  // Auto-generate when panel opens
  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated.current && !fbLoading) {
      hasAutoGenerated.current = true;
      // Small delay to ensure hidden template is rendered
      setTimeout(() => {
        generateRef.current?.();
      }, 300);
    }
  }, [autoGenerate, fbLoading]);

  const connectFacebook = async () => {
    try {
      const resp = await fetch(`${SUPABASE_URL}/functions/v1/facebook-auth-url`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${ANON_KEY}` },
        body: JSON.stringify({ agent_id: user!.id, app_origin: window.location.origin }),
      });
      const data = await resp.json();
      if (data.error) throw new Error(data.error);
      window.open(data.auth_url, '_blank');
    } catch (err: any) {
      toast.error(err.message || 'Failed to start Facebook login');
    }
  };

  // Proxy external image through edge function to bypass CORS
  const toDataUrl = async (url: string): Promise<string> => {
    const resp = await fetch(`${SUPABASE_URL}/functions/v1/proxy-image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${ANON_KEY}` },
      body: JSON.stringify({ url }),
    });
    const data = await resp.json();
    if (data.error) throw new Error(data.error);
    return data.data;
  };


  const generateAd = async () => {
    setGenerating(true);
    try {
      // Pre-load hero photo as data URL to avoid CORS
      let dataUrl = heroDataUrl;
      if (heroPhoto && !dataUrl) {
        try {
          dataUrl = await toDataUrl(heroPhoto);
          setHeroDataUrl(dataUrl);
        } catch {
          console.warn('Could not load hero photo, generating without it');
        }
      }
      const url = await renderAdCanvas({
        listing,
        bannerText,
        heroDataUrl: dataUrl,
        agentPhone,
      });
      setPreviewUrl(url);
      setPosted(false);
      toast.success('Ad generated! Ready to post.');
    } catch (err: any) {
      toast.error('Failed to generate ad image');
      console.error(err);
    }
    setGenerating(false);
  };

  generateRef.current = generateAd;

  const postToFacebook = async () => {
    if (!previewUrl || !user) return;
    setPosting(true);
    try {
      // Convert data URL to blob
      const res = await fetch(previewUrl);
      const blob = await res.blob();
      const fileName = `ad-${listing.mlsNumber || listing.id}-${Date.now()}.png`;

      // Upload to storage
      const { data: uploadData, error: uploadErr } = await supabase.storage
        .from('ad-images')
        .upload(fileName, blob, { contentType: 'image/png', upsert: true });

      if (uploadErr) throw new Error(`Upload failed: ${uploadErr.message}`);

      // Get public URL
      const { data: urlData } = supabase.storage.from('ad-images').getPublicUrl(fileName);
      const publicUrl = urlData.publicUrl;

      // Build OG URL with cache-busting timestamp for fresh metadata on each post
      const timestamp = Math.floor(Date.now() / 1000);
      const ogUrlWithImage = `${ogListingUrl}&image=${encodeURIComponent(publicUrl)}&v=${timestamp}`;

      // Post to Facebook as a link post (shows OG preview card with branded image)
      const price = formatListingPrice(listing.price);
      const message = `🏠 ${bannerText}\n\n📍 ${fullAddress}\n💰 ${price}\n🛏️ ${listing.beds} Beds | 🛁 ${listing.baths} Baths | 📐 ${listing.sqft.toLocaleString()} sqft\n\n👉 More info: ${listingUrl}\n\n📞 Contact ${listing.agent?.name || 'us'} for details!\n\n#RealEstate #${listing.city.replace(/\s/g, '')} #HomeForSale`;

      const postResp = await fetch(`${SUPABASE_URL}/functions/v1/facebook-post-listing`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${ANON_KEY}` },
        body: JSON.stringify({
          agent_id: user.id,
          message,
          link: ogUrlWithImage,
        }),
      });
      const postData = await postResp.json();
      console.log('[FB] Post response:', postData);
      if (postData.error) throw new Error(postData.error);

      const returnedPostId = postData.post_id || postData.id || null;
      console.log('[FB] Setting postId to:', returnedPostId);
      setPosted(true);
      setPostId(returnedPostId);
      
      // Show warning if scrape had issues
      if (postData.warning) {
        toast.info(postData.warning);
      } else {
        toast.success('Ad posted to Facebook! 🎉');
      }
    } catch (err: any) {
      toast.error(err.message || 'Failed to post to Facebook');
    }
    setPosting(false);
  };

  return (
    <div className="bg-card border border-border rounded-lg p-5">
      <div className="flex items-center gap-2 mb-4">
        <Image className="w-5 h-5 text-primary" />
        <h3 className="text-lg font-bold text-card-foreground">Generate & Post Ad</h3>
      </div>

      {/* Facebook connection status */}
      {fbLoading ? (
        <div className="flex items-center gap-2 text-xs text-muted-foreground mb-3">
          <Loader2 className="w-3 h-3 animate-spin" /> Checking Facebook...
        </div>
      ) : fbConnected ? (
        <p className="text-xs text-muted-foreground mb-3 flex items-center gap-1">
          <Check className="w-3 h-3 text-emerald-500" />
          Connected to <span className="font-medium text-foreground">{fbPageName}</span>
        </p>
      ) : (
        <div className="mb-3">
          <Button onClick={connectFacebook} variant="outline" size="sm" className="w-full">
            <Link2 className="w-4 h-4 mr-2" /> Connect Facebook Page First
          </Button>
        </div>
      )}

      <div className="mb-4">
        <label className="text-xs font-medium text-muted-foreground mb-1.5 block">Banner Type</label>
        <Select value={bannerType} onValueChange={setBannerType}>
          <SelectTrigger className="w-full">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {bannerOptions.map(opt => (
              <SelectItem key={opt.value} value={opt.value}>{opt.label}</SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>



      <Button onClick={generateAd} disabled={generating} className="w-full mb-3 !bg-green-600 hover:!bg-green-700 !text-white" size="sm">
        {generating ? (
          <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Generating...</>
        ) : (
          <><Image className="w-4 h-4 mr-2" /> {previewUrl ? 'Regenerate' : 'Generate'} Ad Image</>
        )}
      </Button>

      {previewUrl && (
        <>
          <div className="border border-border rounded-lg overflow-hidden mb-3">
            <img src={previewUrl} alt="Generated ad" className="w-full" />
          </div>

           {fbConnected && (
            <Button
              onClick={postToFacebook}
              disabled={posting || posted}
              className="w-full !bg-green-600 hover:!bg-green-700 !text-white"
              size="sm"
            >
              {posted ? (
                <><Check className="w-4 h-4 mr-2" /> Posted!</>
              ) : posting ? (
                <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Posting...</>
              ) : (
                <><Facebook className="w-4 h-4 mr-2" /> Post Ad to Facebook</>
              )}
            </Button>
           )}
           {postId && (
             <Button
               onClick={() => window.open(`https://www.facebook.com/${postId}`, '_blank')}
               variant="outline"
               className="w-full mt-2"
               size="sm"
             >
               <ExternalLink className="w-4 h-4 mr-2" /> Boost This Post on Facebook
             </Button>
           )}
        </>
      )}
    </div>
  );
};

export default AdGeneratorPanel;
